name: CI - Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download NLTK data
        run: |
          python -c "import nltk; nltk.download('punkt'); nltk.download('punkt_tab'); nltk.download('stopwords'); nltk.download('wordnet')"

      - name: Run tests
        run: |
          python -m pytest tests/ -v

      - name: Test pipeline execution
        run: |
          python pipeline.py --top-k 5

      - name: Check outputs created
        run: |
          ls -la outputs/
          test -f outputs/tags.json
          test -f outputs/feedback.json
          test -f outputs/tag_weights.json
